---
application:
  name: "garage-backend"
  project: "g2"
  organization: "QoveryCommunity"
routers:
- name: "main-garage-backend"
  routes:
  - application_name: "garage-backend"
    paths:
    - "/*"
