---
application:
  name: 'garage-backend'
  project: 'garage'
  organization: 'QoveryCommunity'
  publicly_accessible: true
routers:
  - name: 'main-garage-backend'
    routes:
      - application_name: 'garage-backend'
        paths:
          - '/*'
